/** Hand-checked notes and example sentences. Definitions stay from the source list. */

export const enrichment = {
  abide: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'literary',
    simple_definition: 'stay, or obey when the phrase is abide by',
    synonyms: ['remain', 'stay'],
    near_synonyms: ['endure', 'tolerate'],
    antonyms: ['leave', 'defy'],
    collocations: ['abide by a rule', 'abide in a place'],
    word_family: ['abode', 'abiding'],
    etymology: 'Old English ābīdan, to wait or remain.',
    mnemonic: 'Abide by adds the word by. That by is the obedience.',
    usage_notes:
      'In this list, abide means live or stay, an older use. Abide by means obey or accept. Other modern writing also uses abide to mean tolerate, as in “I cannot abide the noise.” That tolerate sense is not the one this list drills first.',
    common_confusions: [
      'abide alone often means stay or remain in older writing',
      'abide by means obey or accept',
      'cannot abide means cannot tolerate, a different modern use',
    ],
    compare_with: [],
    examples: [
      'The hermit chose to abide in the valley long after the village had emptied.',
      'Every player has to abide by the referee’s decision.',
    ],
    usage_choices: [
      { text: 'Members have to abide by the safety rules.', correct: true, note: 'Abide by means obey or accept.' },
      { text: 'She will abide by the cake until nothing is left.', correct: false, note: 'Abide by does not mean eat or finish.' },
      { text: 'The old cottage is where he chose to abide by the winter.', correct: false, note: 'For staying in a place, use abide, not abide by. By turns it into “obey.”' },
    ],
  },
  abound: {
    part_of_speech: 'verb',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'exist in large numbers',
    synonyms: ['teem', 'proliferate'],
    near_synonyms: ['flourish'],
    antonyms: ['lack', 'dwindle'],
    collocations: ['abound in', 'abound with'],
    word_family: ['abundance', 'abundant'],
    etymology: 'Latin abundare, to overflow.',
    mnemonic: 'A boundless field: so many that you lose count.',
    usage_notes:
      'Abound means exist in large numbers: wildflowers abound. Abound in or abound with means have a lot of something: the reef abounds in color.',
    common_confusions: ['abound (there are many) versus abound in (it has many)'],
    compare_with: [],
    examples: [
      'Wildflowers abound along the riverbank after a wet spring.',
      'The essay abounds in precise, surprising details.',
    ],
    usage_choices: [
      { text: 'Rumors abound whenever the school changes the schedule.', correct: true, note: 'There are a great many rumors.' },
      { text: 'Please abound the chairs into the closet.', correct: false, note: 'Abound is not a word for moving objects.' },
      { text: 'She was abound happy about the grade.', correct: false, note: 'Abound is a verb, not an intensifier like very.' },
    ],
  },
  abrasive: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'general',
    simple_definition: 'harsh in manner, or rough and scraping',
    synonyms: ['harsh', 'grating'],
    near_synonyms: ['curt', 'caustic'],
    antonyms: ['gentle', 'smooth'],
    collocations: ['abrasive manner', 'abrasive surface'],
    word_family: ['abrasion', 'abrade'],
    etymology: 'Latin abradere, to scrape off.',
    mnemonic: 'Sandpaper scrapes. An abrasive person scrapes at your patience the same way.',
    usage_notes:
      'Abrasive can describe a physical surface that scrapes, or a manner that is harsh and irritating. On a reading test, the sentence tells you which sense is meant.',
    common_confusions: ['physical scraping versus a harsh personality'],
    compare_with: [],
    examples: [
      'The clerk’s abrasive reply made the customer leave without buying anything.',
      'The abrasive pad scraped the rust off the pan.',
    ],
    usage_choices: [
      { text: 'His abrasive comments shut down the discussion.', correct: true, note: 'Here abrasive means harsh and irritating.' },
      { text: 'She abrasive the letter into the mailbox.', correct: false, note: 'Abrasive is not a verb meaning send.' },
      { text: 'The soup tasted abrasive, so she added more salt to make it sweeter.', correct: false, note: 'Abrasive does not mean salty or sweet. The physical sense is rough or scraping, and the personal sense is harsh.' },
    ],
  },
  accrete: {
    part_of_speech: 'verb',
    difficulty: 4,
    register: 'formal',
    simple_definition: 'grow by layers being added',
    synonyms: ['accumulate'],
    near_synonyms: ['coalesce', 'build up'],
    antonyms: ['erode', 'shed'],
    collocations: ['accrete layers', 'sediment accretes'],
    word_family: ['accretion'],
    etymology: 'Latin accrescere, to grow onto something.',
    mnemonic: 'Accrete sounds like concrete: layers stick on and the mass gets thicker.',
    usage_notes:
      'Accrete emphasizes layers or pieces being added onto something. Accrue emphasizes a total that builds gradually, often money, time, or advantage. Both can mean slow growth, but the picture is different.',
    common_confusions: ['accrete (layers added on) versus accrue (a total builds up)'],
    compare_with: ['accrue'],
    examples: [
      'Shells and sand accrete into a low ridge along the shore.',
      'Trust does not appear at once; it accretes through small, kept promises.',
    ],
    usage_choices: [
      { text: 'Dust and lint accrete on the fan blades until the motor strains.', correct: true, note: 'Material is added in layers.' },
      { text: 'Interest will accrete by when the judge says so.', correct: false, note: 'That mixes accrete with abide by. Accrete is not about obeying.' },
      { text: 'The fee will accrete on the debt each month.', correct: false, note: 'A running money total is accrue, not accrete.' },
    ],
  },
  accrue: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'build up gradually over time',
    synonyms: ['accumulate'],
    near_synonyms: ['build up'],
    antonyms: ['dwindle'],
    collocations: ['interest accrues', 'benefits accrue'],
    word_family: ['accrual'],
    etymology: 'From Old French, ultimately Latin ad and crescere, to grow.',
    mnemonic: 'Accrue is a running total, like interest quietly added to a balance.',
    usage_notes:
      'Use accrue for a quantity or advantage that builds over time. Use accrete when the image is layers sticking onto something.',
    common_confusions: ['accrue (a total builds) versus accrete (layers are added)'],
    compare_with: ['accrete'],
    examples: [
      'Interest will accrue on the unpaid balance until it is paid.',
      'Small advantages accrue to students who review a little every day.',
    ],
    usage_choices: [
      { text: 'Vacation days accrue the longer she stays with the company.', correct: true, note: 'The total builds gradually.' },
      { text: 'Barnacles accrue by the captain’s order.', correct: false, note: 'Accrue is not a command to obey. Layers of barnacles would accrete.' },
      { text: 'Please accrue the chairs against the wall.', correct: false, note: 'Accrue does not mean move or stack on purpose in this casual way.' },
    ],
  },
  adhere: {
    part_of_speech: 'verb',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'stick to, or follow a rule closely',
    synonyms: ['stick', 'follow'],
    near_synonyms: ['cling', 'comply'],
    antonyms: ['detach', 'abandon'],
    collocations: ['adhere to a rule', 'adhere to a surface'],
    word_family: ['adherence', 'adherent', 'adhesion'],
    etymology: 'Latin adhaerere, to stick to.',
    mnemonic: 'Adhesive tape adheres. People adhere to a plan the way tape sticks.',
    usage_notes: 'Adhere to can be physical (tape adheres to glass) or figurative (adhere to a belief or rule).',
    common_confusions: ['physical sticking versus following a rule'],
    compare_with: ['abide'],
    examples: [
      'The label would not adhere to the damp bottle.',
      'The lab must adhere to the safety protocol without shortcuts.',
    ],
    usage_choices: [
      { text: 'We adhere to the deadline even when the work is difficult.', correct: true, note: 'Adhere to means follow closely.' },
      { text: 'They adhere the rumor into a bigger rumor.', correct: false, note: 'Adhere is not a word for making a story grow. That picture is closer to accrete or accrue.' },
    ],
  },
  adverse: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'harmful or unfavorable',
    synonyms: ['unfavorable', 'harmful'],
    near_synonyms: ['hostile'],
    antonyms: ['favorable', 'beneficial'],
    collocations: ['adverse effects', 'adverse conditions'],
    word_family: ['adversity', 'adversely'],
    etymology: 'Latin adversus, turned against.',
    mnemonic: 'Adverse events come at you. Averse is a feeling inside you.',
    usage_notes: 'Adverse describes conditions, effects, or circumstances that work against someone. Averse describes a person’s strong dislike.',
    common_confusions: ['adverse (harmful conditions) versus averse (a person dislikes something)'],
    compare_with: ['averse'],
    examples: [
      'Adverse weather forced the hikers to turn back.',
      'The leaflet lists adverse effects of the medicine.',
    ],
    usage_choices: [
      { text: 'The experiment failed under adverse conditions.', correct: true, note: 'The conditions were unfavorable.' },
      { text: 'She is adverse to public speaking.', correct: false, note: 'A person’s dislike is averse to, not adverse to.' },
    ],
  },
  averse: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'strongly disliking or opposed',
    synonyms: ['opposed', 'disinclined'],
    near_synonyms: ['reluctant'],
    antonyms: ['eager', 'inclined'],
    collocations: ['averse to risk', 'not averse to'],
    word_family: ['aversion'],
    etymology: 'Latin aversus, turned away.',
    mnemonic: 'I am averse. The feeling belongs to the person, not the weather.',
    usage_notes: 'Averse almost always describes a person or group: averse to risk. Adverse describes the outside situation.',
    common_confusions: ['averse (someone dislikes) versus adverse (something is harmful)'],
    compare_with: ['adverse'],
    examples: [
      'He is averse to any plan that skips the safety check.',
      'She is not averse to hard work, but she hates wasted effort.',
    ],
    usage_choices: [
      { text: 'Investors who are averse to risk choose slower, steadier funds.', correct: true, note: 'The investors dislike risk.' },
      { text: 'Averse winds delayed the flight.', correct: false, note: 'Harmful winds are adverse, not averse.' },
    ],
  },
  appraise: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'judge the value or quality of',
    synonyms: ['assess', 'evaluate'],
    near_synonyms: ['estimate'],
    antonyms: [],
    collocations: ['appraise a property', 'appraise the evidence'],
    word_family: ['appraisal', 'appraiser'],
    etymology: 'Old French aprisier, to set a price, related to price and praise.',
    mnemonic: 'Appraise has praise and price in its history: you judge what something is worth.',
    usage_notes: 'Appraise means judge value or quality. Apprise means inform. The spellings are one letter apart.',
    common_confusions: ['appraise (judge the worth) versus apprise (tell someone)'],
    compare_with: ['apprise'],
    examples: [
      'An expert will appraise the painting before the auction.',
      'She stepped back to appraise the argument with a cooler eye.',
    ],
    usage_choices: [
      { text: 'The jeweler appraised the ring at far less than they had hoped.', correct: true, note: 'Appraise means judge the value.' },
      { text: 'Please appraise me of any change in the schedule.', correct: false, note: 'To inform someone, use apprise. The usual phrase is apprise someone of.' },
    ],
  },
  apprise: {
    part_of_speech: 'verb',
    difficulty: 4,
    register: 'formal',
    simple_definition: 'inform or make aware',
    synonyms: ['inform', 'notify'],
    near_synonyms: ['tell'],
    antonyms: [],
    collocations: ['apprise someone of'],
    word_family: [],
    etymology: 'French apprendre, in the sense of teaching or informing.',
    mnemonic: 'Apprise has an i for inform. Appraise has an a for assess.',
    usage_notes: 'The usual pattern is apprise someone of something. Appraise something means judge its value.',
    common_confusions: ['apprise (inform) versus appraise (judge value)'],
    compare_with: ['appraise'],
    examples: [
      'Please apprise the committee of any conflict of interest.',
      'No one had apprised her of the change in plans.',
    ],
    usage_choices: [
      { text: 'The guide apprised us of the trail closure.', correct: true, note: 'Apprise of means inform about.' },
      { text: 'The guide apprised the cabin at two hundred dollars.', correct: false, note: 'Setting a value is appraise, not apprise.' },
    ],
  },
  allude: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'refer to something indirectly',
    synonyms: ['refer', 'hint'],
    near_synonyms: ['suggest'],
    antonyms: ['state'],
    collocations: ['allude to'],
    word_family: ['allusion', 'allusive'],
    etymology: 'Latin alludere, to play toward or hint at.',
    mnemonic: 'An allusion plays at the idea. Elude means the idea gets away.',
    usage_notes: 'Allude to means hint at something without naming it outright. Elude means escape or be hard to grasp. You allude to a book. A name can elude you.',
    common_confusions: ['allude (hint at) versus elude (escape or be hard to recall)'],
    compare_with: ['elude'],
    examples: [
      'The speaker alluded to the scandal without ever saying the mayor’s name.',
      'Her poem alludes to a famous myth, trusting the reader to notice.',
    ],
    usage_choices: [
      { text: 'He alluded to the contract but refused to quote it.', correct: true, note: 'He referred to it indirectly.' },
      { text: 'The suspect alluded capture by slipping out the back.', correct: false, note: 'Escaping capture is elude, not allude.' },
    ],
  },
  elude: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'escape from, or be hard to grasp',
    synonyms: ['escape', 'evade'],
    near_synonyms: ['dodge'],
    antonyms: ['face', 'capture'],
    collocations: ['elude capture', 'the name eludes me'],
    word_family: ['elusive'],
    etymology: 'Latin eludere, to finish playing or evade.',
    mnemonic: 'If it eludes you, it got away. If you allude to it, you hinted at it.',
    usage_notes: 'Elude can mean physically escape, or stay just out of understanding or memory. Allude always means hint.',
    common_confusions: ['elude (escape) versus allude (hint)'],
    compare_with: ['allude'],
    examples: [
      'The solution eluded her until she reread the last paragraph.',
      'The fox eluded the hounds by doubling back through the creek.',
    ],
    usage_choices: [
      { text: 'The answer eluded him no matter how long he stared at the chart.', correct: true, note: 'The answer was hard to grasp.' },
      { text: 'She eluded to the chart without explaining it.', correct: false, note: 'Hinting uses allude to, not elude to.' },
    ],
  },
  ambiguous: {
    part_of_speech: 'adjective',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'open to more than one meaning',
    synonyms: ['unclear', 'equivocal'],
    near_synonyms: ['vague'],
    antonyms: ['clear', 'explicit'],
    collocations: ['ambiguous wording', 'deliberately ambiguous'],
    word_family: ['ambiguity'],
    etymology: 'Latin ambiguus, doubtful, from ambigere, to wander around.',
    mnemonic: 'Two roads at once: an ambiguous sentence can go either way.',
    usage_notes: 'Ambiguous means more than one reading is possible. Ambivalent means having mixed feelings. A sentence can be ambiguous. A person is ambivalent.',
    common_confusions: ['ambiguous (unclear meaning) versus ambivalent (mixed feelings)'],
    compare_with: ['ambivalent'],
    examples: [
      'The ending is ambiguous, so readers argue about what the last line means.',
      'Ambiguous instructions caused half the class to skip the second step.',
    ],
    usage_choices: [
      { text: 'The pronoun is ambiguous because it could refer to either sister.', correct: true, note: 'The meaning is open.' },
      { text: 'She felt ambiguous about leaving home.', correct: false, note: 'Mixed feelings are ambivalent, not ambiguous.' },
    ],
  },
  ambivalent: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'having mixed or conflicting feelings',
    synonyms: ['conflicted', 'unsure'],
    near_synonyms: ['torn'],
    antonyms: ['certain', 'wholehearted'],
    collocations: ['ambivalent about', 'deeply ambivalent'],
    word_family: ['ambivalence'],
    etymology: 'Latin ambi, both, and valere, to be strong: pulled hard both ways.',
    mnemonic: 'Ambi means both. Ambivalent is strength on both sides of a feeling.',
    usage_notes: 'Ambivalent describes feelings. Ambiguous describes language or evidence that can be read in more than one way.',
    common_confusions: ['ambivalent (mixed feelings) versus ambiguous (unclear meaning)'],
    compare_with: ['ambiguous'],
    examples: [
      'She was ambivalent about the award: proud, and uneasy about the attention.',
      'His ambivalent shrug told them he had not decided.',
    ],
    usage_choices: [
      { text: 'Voters are ambivalent about the plan and can argue either side.', correct: true, note: 'The feelings conflict.' },
      { text: 'The ballot question is ambivalent and can be read two ways.', correct: false, note: 'Wording that can be read two ways is ambiguous.' },
    ],
  },
  anomaly: {
    part_of_speech: 'noun',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'something that departs from what is normal',
    synonyms: ['exception', 'oddity'],
    near_synonyms: ['irregularity'],
    antonyms: ['norm'],
    collocations: ['statistical anomaly', 'an anomaly in the data'],
    word_family: ['anomalous', 'anomalously'],
    etymology: 'Greek anomalos, uneven.',
    mnemonic: 'Not the normal pattern: an anomaly sticks out of the row.',
    usage_notes: 'An anomaly is the odd case itself. Anomalous is the adjective: an anomalous result.',
    common_confusions: ['anomaly (the unusual thing) versus analogous (comparable)'],
    compare_with: [],
    examples: [
      'The warm day in January was an anomaly, not a new climate pattern.',
      'One anomalous spike in the data turned out to be a broken sensor.',
    ],
    usage_choices: [
      { text: 'Her perfect score was an anomaly in an otherwise ordinary season.', correct: true, note: 'It departed from the usual pattern.' },
      { text: 'The two poems are an anomaly to each other in structure.', correct: false, note: 'A comparison of likeness is an analogy. An anomaly is an odd exception.' },
    ],
  },
  appease: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'calm someone by giving in to a demand',
    synonyms: ['placate', 'mollify'],
    near_synonyms: ['soothe'],
    antonyms: ['provoke', 'anger'],
    collocations: ['appease a critic', 'policy of appeasement'],
    word_family: ['appeasement'],
    etymology: 'Old French apaisier, to bring to peace.',
    mnemonic: 'Appease buys peace by giving something up.',
    usage_notes: 'Appease often implies calming a person by concession, not merely becoming quiet yourself.',
    common_confusions: ['appease (calm someone by giving in) versus please (make happy in a general way)'],
    compare_with: [],
    examples: [
      'The council tried to appease the protesters by delaying the vote.',
      'Offering a refund did little to appease the furious customer.',
    ],
    usage_choices: [
      { text: 'They changed the rule to appease the parents who had complained.', correct: true, note: 'They gave in so the parents would calm down.' },
      { text: 'The lake was appease and still at dawn.', correct: false, note: 'Appease is a verb about calming someone, not an adjective meaning peaceful.' },
    ],
  },
  arbitrary: {
    part_of_speech: 'adjective',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'based on whim rather than a fair reason',
    synonyms: ['random', 'capricious'],
    near_synonyms: ['unreasoned'],
    antonyms: ['reasoned', 'principled'],
    collocations: ['arbitrary decision', 'arbitrary rule'],
    word_family: ['arbitrarily', 'arbitrariness'],
    etymology: 'Latin arbiter, a judge. Arbitrary came to mean a decision that is personal rather than principled.',
    mnemonic: 'An arbitrary rule feels pulled out of a hat.',
    usage_notes: 'Arbitrary does not simply mean “any” in careful writing. It criticizes a choice as lacking a fair principle.',
    common_confusions: ['arbitrary (no fair reason) versus random (left to chance, sometimes neutrally)'],
    compare_with: [],
    examples: [
      'The penalty seemed arbitrary because similar mistakes had gone unpunished.',
      'She refused to follow an arbitrary dress code with no safety purpose.',
    ],
    usage_choices: [
      { text: 'Cutting one essay and not the others felt arbitrary.', correct: true, note: 'There was no fair reason for the difference.' },
      { text: 'Please arbitrary the chairs before the guests arrive.', correct: false, note: 'Arbitrary is not a verb meaning arrange.' },
    ],
  },
  archaic: {
    part_of_speech: 'adjective',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'very old or old-fashioned',
    synonyms: ['outdated', 'antiquated'],
    near_synonyms: ['obsolete'],
    antonyms: ['modern', 'current'],
    collocations: ['archaic language', 'archaic law'],
    word_family: ['archaism'],
    etymology: 'Greek arkhaios, ancient, from arkhe, beginning.',
    mnemonic: 'An archaic word belongs in an old poem, not in a text message.',
    usage_notes: 'Archaic language is old-fashioned, like thou or ere. Ancient can describe the time itself. Archaic often describes a survival from that time into the present.',
    common_confusions: ['archaic (old-fashioned, still sometimes seen) versus ancient (belonging to the distant past)'],
    compare_with: [],
    examples: [
      'The contract still uses archaic phrases that no one says aloud.',
      'Thou and ere are archaic forms you will meet in older poetry.',
    ],
    usage_choices: [
      { text: 'The law’s archaic wording confused the new clerk.', correct: true, note: 'The wording is old-fashioned.' },
      { text: 'She archaic the file and saved it.', correct: false, note: 'Archaic is an adjective, not a verb meaning archive.' },
    ],
  },
  arduous: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'very difficult and tiring',
    synonyms: ['strenuous', 'grueling'],
    near_synonyms: ['taxing'],
    antonyms: ['easy', 'effortless'],
    collocations: ['arduous journey', 'arduous task'],
    word_family: ['arduously'],
    etymology: 'Latin arduus, steep or difficult to climb.',
    mnemonic: 'Arduous is a steep climb, even when the work is not on a hill.',
    usage_notes: 'Arduous stresses sustained effort, not a brief annoyance.',
    common_confusions: ['arduous (hard and tiring) versus ardent (passionate)'],
    compare_with: [],
    examples: [
      'The arduous hike took nine hours and every scrap of water they carried.',
      'Revising the whole book was arduous, but the argument got clearer.',
    ],
    usage_choices: [
      { text: 'Moving the piano up three flights was arduous work.', correct: true, note: 'The work was difficult and tiring.' },
      { text: 'She gave him an arduous smile of pure joy.', correct: false, note: 'Arduous does not mean warm or loving.' },
    ],
  },
  auspicious: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'favorable, promising success',
    synonyms: ['favorable', 'promising'],
    near_synonyms: ['propitious'],
    antonyms: ['ominous', 'unfavorable'],
    collocations: ['an auspicious start', 'auspicious circumstances'],
    word_family: ['auspiciously'],
    etymology: 'Latin auspicium, the practice of reading bird flight as an omen.',
    mnemonic: 'An auspicious start feels like a good omen.',
    usage_notes: 'Auspicious describes conditions that promise success. Suspicious describes distrust.',
    common_confusions: ['auspicious (promising) versus suspicious (distrustful)'],
    compare_with: [],
    examples: [
      'A clear sky and a full crew made for an auspicious launch.',
      'The opening sales were auspicious, though one week cannot prove a trend.',
    ],
    usage_choices: [
      { text: 'They took the early applause as an auspicious sign.', correct: true, note: 'It seemed to promise success.' },
      { text: 'The guard was auspicious of every visitor’s bag.', correct: false, note: 'Distrust is suspicious, not auspicious.' },
    ],
  },
  bolster: {
    part_of_speech: 'verb',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'support or strengthen',
    synonyms: ['support', 'reinforce'],
    near_synonyms: ['prop up'],
    antonyms: ['undermine', 'weaken'],
    collocations: ['bolster a claim', 'bolster confidence'],
    word_family: [],
    etymology: 'Originally a long pillow. The verb grew from the idea of propping something up.',
    mnemonic: 'A bolster is a pillow that props you up. Evidence can bolster a claim the same way.',
    usage_notes: 'Bolster and buttress both mean support. Bolster is common for confidence, arguments, and morale. Buttress often suggests a firmer structural support.',
    common_confusions: ['bolster versus buttress: both support; buttress sounds more structural'],
    compare_with: ['buttress'],
    examples: [
      'The new study bolsters the claim that sleep improves memory.',
      'A kind note from her coach bolstered her confidence before the match.',
    ],
    usage_choices: [
      { text: 'Two independent experiments bolster the theory.', correct: true, note: 'They strengthen it.' },
      { text: 'The theory was bolster and could not stand.', correct: false, note: 'Bolster is a verb here, and it means support, not collapse.' },
    ],
  },
  buttress: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'support or strengthen',
    synonyms: ['support', 'reinforce'],
    near_synonyms: ['brace'],
    antonyms: ['undermine'],
    collocations: ['buttress an argument', 'flying buttress'],
    word_family: [],
    etymology: 'A buttress is an architectural support built against a wall. The verb means to support in that firm way.',
    mnemonic: 'Picture a stone brace against a cathedral wall: it buttresses the building.',
    usage_notes: 'As a noun, a buttress is a support on a building. As a verb, it means strengthen an argument, system, or structure.',
    common_confusions: ['buttress versus bolster: close synonyms; buttress often feels more structural'],
    compare_with: ['bolster'],
    examples: [
      'The lawyer buttressed her case with three written statements.',
      'Stone buttresses hold the old church walls in place.',
    ],
    usage_choices: [
      { text: 'Extra interviews buttressed the reporter’s conclusion.', correct: true, note: 'They supported the conclusion.' },
      { text: 'The rain buttressed the picnic into the house.', correct: false, note: 'Buttress does not mean move or cancel.' },
    ],
  },
  burgeoning: {
    part_of_speech: 'adjective',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'growing or expanding rapidly',
    synonyms: ['growing', 'flourishing'],
    near_synonyms: ['booming'],
    antonyms: ['shrinking', 'dwindling'],
    collocations: ['burgeoning industry', 'burgeoning interest'],
    word_family: ['burgeon'],
    etymology: 'Old French bourgeon, a bud. To burgeon is to bud and then grow quickly.',
    mnemonic: 'A burgeoning city is budding: new growth everywhere.',
    usage_notes: 'Burgeoning describes rapid growth already underway, not a single finished increase.',
    common_confusions: ['burgeoning (growing fast) versus burdensome (heavy and troublesome)'],
    compare_with: [],
    examples: [
      'The burgeoning neighborhood added a bakery, a clinic, and two bus lines in one year.',
      'Her burgeoning interest in geology started with a single cracked rock.',
    ],
    usage_choices: [
      { text: 'A burgeoning market for repair shops followed the new bus line.', correct: true, note: 'The market is growing quickly.' },
      { text: 'The burgeoning suitcase would not close.', correct: false, note: 'Too full is not burgeoning. Burgeoning means growing, usually a trend, place, or interest.' },
    ],
  },
  waive: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'give up a right or requirement',
    synonyms: ['relinquish', 'forgo'],
    near_synonyms: ['surrender'],
    antonyms: ['enforce', 'claim'],
    collocations: ['waive a fee', 'waive the right'],
    word_family: ['waiver'],
    etymology: 'Anglo-French weyver, to abandon. A waiver is the document that records the giving up.',
    mnemonic: 'Waive has an i, like signing away a right. Waver shakes and hesitates.',
    usage_notes: 'Waive means officially give something up. Waver means hesitate or flicker.',
    common_confusions: ['waive (give up a right) versus waver (hesitate or flicker)'],
    compare_with: ['waver'],
    examples: [
      'The college will waive the application fee for students who ask.',
      'By signing, she waived the right to sue over that clause.',
    ],
    usage_choices: [
      { text: 'The library waived the late fine after hearing the explanation.', correct: true, note: 'They gave up the requirement to pay.' },
      { text: 'The candle flame waived in the draft.', correct: false, note: 'A flame that moves unsteadily wavers.' },
    ],
  },
  waver: {
    part_of_speech: 'verb',
    difficulty: 2,
    register: 'general',
    simple_definition: 'hesitate, or move unsteadily',
    synonyms: ['hesitate', 'falter'],
    near_synonyms: ['flicker'],
    antonyms: ['persist', 'decide'],
    collocations: ['waver between', 'never wavered'],
    word_family: ['wavering'],
    etymology: 'Related to wave: a motion that goes back and forth.',
    mnemonic: 'Waver waves. Waive signs a right away.',
    usage_notes: 'Waver can describe a light or voice that flickers, or a person who cannot decide.',
    common_confusions: ['waver (hesitate) versus waive (give up a right)'],
    compare_with: ['waive'],
    examples: [
      'She did not waver once the evidence was in front of her.',
      'The candle flame wavered and then went out.',
    ],
    usage_choices: [
      { text: 'He wavered between the two colleges until April.', correct: true, note: 'He hesitated.' },
      { text: 'The judge wavered the fee for the defendant.', correct: false, note: 'Giving up a fee is waive, not waver.' },
    ],
  },
  unexceptionable: {
    part_of_speech: 'adjective',
    difficulty: 5,
    register: 'formal',
    simple_definition: 'beyond criticism',
    synonyms: ['unobjectionable', 'irreproachable'],
    near_synonyms: ['acceptable'],
    antonyms: ['objectionable'],
    collocations: ['unexceptionable conduct', 'unexceptionable taste'],
    word_family: [],
    etymology: 'Exception in the sense of an objection: unexceptionable means no objection can be taken.',
    mnemonic: 'Unexceptionable means you cannot take exception to it. Unexceptional means ordinary.',
    usage_notes:
      'Unexceptionable means beyond criticism, not “ordinary.” Unexceptional means not exceptional, so ordinary. The source list flags this pair on purpose.',
    common_confusions: ['unexceptionable (beyond criticism) versus unexceptional (ordinary)'],
    compare_with: [],
    examples: [
      'His conduct was unexceptionable: polite, exact, and impossible to fault.',
      'The prose is unexceptionable, correct in every line, and a little dull.',
    ],
    usage_choices: [
      { text: 'No one could criticize her unexceptionable manners.', correct: true, note: 'There was nothing to object to.' },
      { text: 'It was an unexceptionable Tuesday, ordinary in every way.', correct: false, note: 'Ordinary is unexceptional. Unexceptionable means beyond criticism.' },
    ],
  },
  aggravate: {
    part_of_speech: 'verb',
    difficulty: 2,
    register: 'general',
    simple_definition: 'make worse; also annoy',
    synonyms: ['worsen'],
    near_synonyms: ['annoy', 'irritate'],
    antonyms: ['soothe', 'improve'],
    collocations: ['aggravate an injury', 'aggravate the problem'],
    word_family: ['aggravation'],
    etymology: 'Latin aggravare, to make heavier.',
    mnemonic: 'Aggravate adds gravity: the problem gets heavier.',
    usage_notes:
      'In formal writing, aggravate means make worse. In everyday speech it also means annoy. On a reading test, check which sense the sentence earns.',
    common_confusions: ['make a problem worse versus annoy a person'],
    compare_with: [],
    examples: [
      'Walking on the sprain only aggravated the injury.',
      'The constant tapping aggravated everyone in the quiet car.',
    ],
    usage_choices: [
      { text: 'Adding unverified numbers aggravated the confusion in the report.', correct: true, note: 'It made the confusion worse.' },
      { text: 'The cream aggravated the cut until it closed.', correct: false, note: 'If the cut healed, it was not aggravated. Aggravate would make it worse.' },
    ],
  },
  amiable: {
    part_of_speech: 'adjective',
    difficulty: 2,
    register: 'general',
    simple_definition: 'friendly and pleasant',
    synonyms: ['friendly', 'genial'],
    near_synonyms: ['affable', 'good-natured'],
    antonyms: ['hostile', 'sullen'],
    collocations: ['an amiable host', 'amiable smile'],
    word_family: ['amiably', 'amiability'],
    etymology: 'Latin amicabilis, friendly, from amicus, friend.',
    mnemonic: 'Amiable sounds like amigo: friendly.',
    usage_notes: 'Amiable describes a friendly manner. Amicable often describes a relationship that stays peaceable, as in an amicable agreement. This list’s headword is amiable.',
    common_confusions: ['amiable (friendly person) versus amicable (a peaceable relationship or agreement)'],
    compare_with: [],
    examples: [
      'The amiable guide remembered every hiker’s name.',
      'An amiable argument over the map never turned sharp.',
    ],
    usage_choices: [
      { text: 'Our amiable neighbor brought soup when we were sick.', correct: true, note: 'The neighbor is friendly and pleasant.' },
      { text: 'The rock was amiable and hard to lift.', correct: false, note: 'Amiable does not mean heavy or difficult.' },
    ],
  },
  amorphous: {
    part_of_speech: 'adjective',
    difficulty: 4,
    register: 'formal',
    simple_definition: 'shapeless, without clear structure',
    synonyms: ['shapeless', 'formless'],
    near_synonyms: ['vague'],
    antonyms: ['structured', 'defined'],
    collocations: ['an amorphous plan', 'amorphous mass'],
    word_family: [],
    etymology: 'Greek amorphos, without form. A- means without, morphe means shape.',
    mnemonic: 'A-morph: no morph, no shape.',
    usage_notes: 'Amorphous can describe a physical blob or a plan, group, or idea with no clear structure.',
    common_confusions: ['amorphous (no shape) versus enormous (very large)'],
    compare_with: [],
    examples: [
      'The committee’s goal stayed amorphous: everyone nodded, and no one could state it.',
      'An amorphous cloud of ink spread through the water.',
    ],
    usage_choices: [
      { text: 'Without an outline, the essay remained amorphous.', correct: true, note: 'It had no clear structure.' },
      { text: 'The amorphous athlete broke the school record.', correct: false, note: 'Amorphous does not mean strong or famous.' },
    ],
  },
  animosity: {
    part_of_speech: 'noun',
    difficulty: 2,
    register: 'formal',
    simple_definition: 'strong dislike or hostility',
    synonyms: ['hostility', 'enmity'],
    near_synonyms: ['resentment'],
    antonyms: ['goodwill', 'friendship'],
    collocations: ['personal animosity', 'animosity between'],
    word_family: ['animosities'],
    etymology: 'Latin animus, spirit or passion. The word narrowed toward hostile feeling.',
    mnemonic: 'Animosity is an angry spirit between people, not a lively mood.',
    usage_notes: 'Animosity is the feeling of hostility. It is stronger and more personal than a mild dislike.',
    common_confusions: ['animosity (hostility) versus animation (liveliness)'],
    compare_with: [],
    examples: [
      'Years of animosity between the two coaches showed in every interview.',
      'She felt no animosity toward the rival who had beaten her fairly.',
    ],
    usage_choices: [
      { text: 'Old animosity made the negotiation slower than it needed to be.', correct: true, note: 'Hostility got in the way.' },
      { text: 'The animosity of the music made the children dance.', correct: false, note: 'Liveliness is not animosity. Animosity is hostile feeling.' },
    ],
  },
  ascertain: {
    part_of_speech: 'verb',
    difficulty: 3,
    register: 'formal',
    simple_definition: 'find out for certain',
    synonyms: ['determine', 'establish'],
    near_synonyms: ['verify', 'discover'],
    antonyms: ['guess'],
    collocations: ['ascertain the facts', 'ascertain whether'],
    word_family: [],
    etymology: 'Old French acertener, to make certain.',
    mnemonic: 'Ascertain ends in certain: you find out until you are sure.',
    usage_notes: 'Ascertain is more formal than find out, and it stresses becoming certain rather than merely looking.',
    common_confusions: ['ascertain (find out for sure) versus assert (state confidently)'],
    compare_with: [],
    examples: [
      'The clerk called the bank to ascertain whether the check was real.',
      'Before they blamed the sensor, they ascertained that the battery was charged.',
    ],
    usage_choices: [
      { text: 'Reporters still need to ascertain the time of the meeting.', correct: true, note: 'They need to find it out for certain.' },
      { text: 'He ascertained his opinion loudly enough for the whole room.', correct: false, note: 'Stating an opinion confidently is assert, not ascertain.' },
    ],
  },
}

export const archaicPos = {
  thou: 'pronoun',
  ye: 'pronoun',
  hast: 'verb',
  camest: 'verb',
  beginneth: 'verb',
  "'tis": 'contraction',
  "o'er": 'contraction',
  "e'en": 'contraction',
  ere: 'conjunction',
  'ought (aught)': 'pronoun',
  anon: 'adverb',
  'hither and thither': 'phrase',
  withal: 'adverb',
  straightway: 'adverb',
  "o'erween": 'verb',
  morn: 'noun',
  wax: 'verb',
  drear: 'adjective',
  wold: 'noun',
  lea: 'noun',
  bower: 'noun',
  abysm: 'noun',
  beweep: 'verb',
  gladsome: 'adjective',
  beauteous: 'adjective',
  plaint: 'noun',
  guerdon: 'noun',
  jackanapes: 'noun',
  coxcombical: 'adjective',
  plashing: 'verb',
}
